#pragma once
#include <Windows.h>

LRESULT CALLBACK CntrlBtnProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK WndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK ShProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK ConProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK AnFldProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK KeyProc(int nCode, WPARAM wParam, LPARAM lParam);